const projects = [
  ["projects"],
  {
    name: "sorting visualizer",
    path: "javascript:void(0)",
    text: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Rerum eveniet amet odit aperiam, provident cum possimus sapiente minus quos! Ipsum?",
    github: "javascript:void(0)",
    image: "./images/project-1.jpeg",
  },
  {
    name: "path finding visualizer",
    path: "javascript:void(0)",
    text: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Rerum eveniet amet odit aperiam, provident cum possimus sapiente minus quos! Ipsum?",
    github: "javascript:void(0)",
    image: "./images/project-1.jpeg",
  },
  {
    name: "e-commerce site",
    path: "javascript:void(0)",
    text: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Rerum eveniet amet odit aperiam, provident cum possimus sapiente minus quos! Ipsum?",
    github: "javascript:void(0)",
    image: "./images/project-1.jpeg",
  },
  {
    name: "chatBiz",
    path: "javascript:void(0)",
    text: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Rerum eveniet amet odit aperiam, provident cum possimus sapiente minus quos! Ipsum?",
    github: "javascript:void(0)",
    image: "./images/project-1.jpeg",
  },
  {
    name: "Portfolio",
    path: "javascript:void(0)",
    text: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Rerum eveniet amet odit aperiam, provident cum possimus sapiente minus quos! Ipsum?",
    github: "javascript:void(0)",
    image: "./images/project-1.jpeg",
  },

  ["react projects"],

  {
    name: "birthday reminder",
    path: "https://chirag-08x.github.io/birthday-reminder/",
    text: "A simple birthday reminder app which lets you know when your birthday is.",
    github: "https://github.com/chirag-08x/birthday-reminder/tree/master",
    image: "./images/react-project-img/prjct-1.png",
  },
  {
    name: "tours",
    path: "https://chirag-08x.github.io/Tours/",
    text: "A simple tours app which lets you explore countries around the world.",
    github: "https://github.com/chirag-08x/Tours/tree/master",
    image: "./images/react-project-img/prjct-2.png",
  },
  {
    name: "reviews",
    path: "https://chirag-08x.github.io/React-Reviews/",
    text: "A simple review app which lets you read people reviews.",
    github: "https://github.com/chirag-08x/React-Reviews/tree/master",
    image: "./images/react-project-img/prjct-3.png",
  },
  {
    name: "accordion(FAQ)",
    path: "https://chirag-08x.github.io/Accordion/",
    text: "A simple accordion where you can see frequently asked questions.",
    github: "https://github.com/chirag-08x/Accordion/tree/master",
    image: "./images/react-project-img/prjct-4.png",
  },
  {
    name: "menu",
    path: "https://chirag-08x.github.io/react-menu/",
    text: "A simple restaurant menu where you can filter out dishes.",
    github: "https://github.com/chirag-08x/react-menu/tree/master",
    image: "./images/react-project-img/prjct-5.png",
  },
  {
    name: "tabs",
    path: "https://chirag-08x.github.io/React-Tabs/",
    text: "A simple apps that lets you switch between Tabs, built using React.",
    github: "https://github.com/chirag-08x/React-Tabs/tree/master",
    image: "./images/react-project-img/prjct-6.png",
  },
  {
    name: "slider",
    path: "javascript:void(0)",
    text: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Rerum eveniet amet odit aperiam, provident cum possimus sapiente minus quos! Ipsum?",
    github: "javascript:void(0)",
    image: "./images/project-1.jpeg",
  },
  {
    name: "lorem ipsum",
    path: "https://chirag-08x.github.io/React-Lorem-Generator/",
    text: "A simple Lorem Ipsum Generator App where you can choose the number of lorem ipsum paragraphs you want and the app will generate it, built using React.",
    github: "https://github.com/chirag-08x/React-Lorem-Generator/tree/master",
    image: "./images/react-project-img/prjct-8.png",
  },
  {
    name: "color generator",
    path: "https://chirag-08x.github.io/Color-Generator/",
    text: "A simple color generator app which generates 20 shades of any given color value.",
    github: "https://github.com/chirag-08x/Color-Generator/tree/master)",
    image: "./images/react-project-img/prjct-9.png",
  },
  {
    name: "grocery bud",
    path: "https://chirag-08x.github.io/React-Grocery-Bud/",
    text: "A simple Grocery List App where you can add, remove, edit, items in the grocery list.",
    github: "https://github.com/chirag-08x/React-Grocery-Bud/tree/master",
    image: "./images/react-project-img/prjct-10.png",
  },
  {
    name: "navbar",
    path: "javascript:void(0)",
    text: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Rerum eveniet amet odit aperiam, provident cum possimus sapiente minus quos! Ipsum?",
    github: "javascript:void(0)",
    image: "./images/project-1.jpeg",
  },
  {
    name: "sidebar and modal",
    path: "javascript:void(0)",
    text: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Rerum eveniet amet odit aperiam, provident cum possimus sapiente minus quos! Ipsum?",
    github: "javascript:void(0)",
    image: "./images/project-1.jpeg",
  },
  {
    name: "stripe menu",
    path: "javascript:void(0)",
    text: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Rerum eveniet amet odit aperiam, provident cum possimus sapiente minus quos! Ipsum?",
    github: "javascript:void(0)",
    image: "./images/project-1.jpeg",
  },
  {
    name: "cart",
    path: "javascript:void(0)",
    text: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Rerum eveniet amet odit aperiam, provident cum possimus sapiente minus quos! Ipsum?",
    github: "javascript:void(0)",
    image: "./images/project-1.jpeg",
  },
  {
    name: "cocktails",
    path: "javascript:void(0)",
    text: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Rerum eveniet amet odit aperiam, provident cum possimus sapiente minus quos! Ipsum?",
    github: "javascript:void(0)",
    image: "./images/project-1.jpeg",
  },
  {
    name: "markdown preview",
    path: "javascript:void(0)",
    text: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Rerum eveniet amet odit aperiam, provident cum possimus sapiente minus quos! Ipsum?",
    github: "javascript:void(0)",
    image: "./images/project-1.jpeg",
  },
  {
    name: "random person",
    path: "javascript:void(0)",
    text: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Rerum eveniet amet odit aperiam, provident cum possimus sapiente minus quos! Ipsum?",
    github: "javascript:void(0)",
    image: "./images/project-1.jpeg",
  },
  {
    name: "pagination",
    path: "javascript:void(0)",
    text: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Rerum eveniet amet odit aperiam, provident cum possimus sapiente minus quos! Ipsum?",
    github: "javascript:void(0)",
    image: "./images/project-1.jpeg",
  },
  {
    name: "infinite scroll",
    path: "javascript:void(0)",
    text: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Rerum eveniet amet odit aperiam, provident cum possimus sapiente minus quos! Ipsum?",
    github: "javascript:void(0)",
    image: "./images/project-1.jpeg",
  },
  {
    name: "stock photos",
    path: "javascript:void(0)",
    text: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Rerum eveniet amet odit aperiam, provident cum possimus sapiente minus quos! Ipsum?",
    github: "javascript:void(0)",
    image: "./images/project-1.jpeg",
  },
  {
    name: "dark mode",
    path: "javascript:void(0)",
    text: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Rerum eveniet amet odit aperiam, provident cum possimus sapiente minus quos! Ipsum?",
    github: "javascript:void(0)",
    image: "./images/project-1.jpeg",
  },
  {
    name: "movies db",
    path: "javascript:void(0)",
    text: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Rerum eveniet amet odit aperiam, provident cum possimus sapiente minus quos! Ipsum?",
    github: "javascript:void(0)",
    image: "./images/project-1.jpeg",
  },
  {
    name: "hacker news",
    path: "javascript:void(0)",
    text: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Rerum eveniet amet odit aperiam, provident cum possimus sapiente minus quos! Ipsum?",
    github: "javascript:void(0)",
    image: "./images/project-1.jpeg",
  },
  {
    name: "quiz",
    path: "javascript:void(0)",
    text: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Rerum eveniet amet odit aperiam, provident cum possimus sapiente minus quos! Ipsum?",
    github: "javascript:void(0)",
    image: "./images/project-1.jpeg",
  },
  ["javascript projects"],
  {
    name: "color flipper",
    path: "https://chirag-08x.github.io/Color-Filpper/",
    text: "A simple color flipper app that will generate new color on every click.",
    github: "https://github.com/chirag-08x/Color-Filpper",
    image: "./images/js-project-img/prjct-1.png",
  },
  {
    name: "counter",
    path: "https://chirag-08x.github.io/Counter/",
    text: "A simple counter app where you can increase or decrease current number by 1 and can also set it back to default 0.",
    github: "https://github.com/chirag-08x/Counter",
    image: "./images/js-project-img/prjct-2.png",
  },
  {
    name: "reviews/quotes",
    path: "https://chirag-08x.github.io/Reviews/",
    text: "A simple app that reviews people.",
    github: "https://github.com/chirag-08x/Reviews",
    image: "./images/js-project-img/prjct-3.png",
  },
  {
    name: "navbar",
    path: "https://chirag-08x.github.io/Navbar/",
    text: "A simple responsive fully functional Navbar.",
    github: "https://github.com/chirag-08x/Navbar",
    image: "./images/js-project-img/prjct-4.png",
  },
  {
    name: "sidebar",
    path: "https://chirag-08x.github.io/Sidebar/",
    text: "A simple responsive fully functional Sidebar.",
    github: "https://github.com/chirag-08x/Sidebar",
    image: "./images/js-project-img/prjct-5.png",
  },
  {
    name: "modal",
    path: "https://chirag-08x.github.io/Modal/",
    text: "A simple responsive fully functional Sidebar.",
    github: "https://github.com/chirag-08x/Modal",
    image: "./images/js-project-img/prjct-6.png",
  },
  {
    name: "QnA",
    path: "https://chirag-08x.github.io/QnA/",
    text: "Question and Answer App.",
    github: "https://github.com/chirag-08x/QnA",
    image: "./images/js-project-img/prjct-7.png",
  },
  {
    name: "menu",
    path: "https://chirag-08x.github.io/Menu/",
    text: "A simple food and drinks menu app where you can choose variety of foods and drinks of your choice.",
    github: "https://github.com/chirag-08x/Menu",
    image: "./images/js-project-img/prjct-8.png",
  },
  {
    name: "video",
    path: "https://chirag-08x.github.io/Video/",
    text: "A simple video app where you can play and pause a video.",
    github: "https://github.com/chirag-08x/Video",
    image: "./images/js-project-img/prjct-9.png",
  },
  {
    name: "tabs",
    path: "https://chirag-08x.github.io/Tabs/",
    text: "A simple page that has multiple tabs where you can switch.",
    github: "https://github.com/chirag-08x/Tabs",
    image: "./images/js-project-img/prjct-10.png",
  },
  {
    name: "smooth scroll",
    path: "https://chirag-08x.github.io/Smooth-Scroll/",
    text: "A simple smooth scroll app where you can smoothly scroll through a page.",
    github: "https://github.com/chirag-08x/Smooth-Scroll",
    image: "./images/js-project-img/prjct-11.png",
  },
  {
    name: "countdown timer",
    path: "https://chirag-08x.github.io/Countdown/",
    text: "A countdown timer where you can set the time backwards.",
    github: "https://github.com/chirag-08x/Countdown",
    image: "./images/js-project-img/prjct-12.png",
  },
  {
    name: "lorem-ipsum generator",
    path: "https://chirag-08x.github.io/Lorem-Ipsum-Generator/",
    text: "A simple app where you can generate lorem ipsum paragraphs.",
    github: "https://github.com/chirag-08x/Lorem-Ipsum-Generator",
    image: "./images/js-project-img/prjct-13.png",
  },
  {
    name: "grocery bud",
    path: "https://chirag-08x.github.io/Grocery-Bud/",
    text: "A simple cart where you can add, edit or remove items of your choice.",
    github: "https://github.com/chirag-08x/Grocery-Bud",
    image: "./images/js-project-img/prjct-14.png",
  },
  {
    name: "slider",
    path: "https://chirag-08x.github.io/ES6-Slider/",
    text: "A simple slider which let's you switch between photos smoothly.",
    github: "https://github.com/chirag-08x/ES6-Slider",
    image: "./images/js-project-img/prjct-15.png",
  },
  {
    name: "random jokes",
    path: "https://chuck-random-joke.netlify.app/",
    text: "Random Chuck Norris Jokes fetched using Random Jokes API.",
    github: "https://github.com/chirag-08x/Random-Joke",
    image: "./images/js-project-img/prjct-16.png",
  },
  {
    name: "random user",
    path: "https://random-usr.netlify.app/",
    text: "Random user fetching using Random user API.",
    github: "https://github.com/chirag-08x/Random-User",
    image: "./images/js-project-img/prjct-17.png",
  },
  {
    name: "cocktails API",
    path: "https://cocktail-ajax.netlify.app/",
    text: "Simple Cocktail App where you can search and find details about your favorite cocktails.",
    github: "https://github.com/chirag-08x/Cocktails",
    image: "./images/js-project-img/prjct-18.png",
  },
  ["HTML/CSS Projects"],
  {
    name: "tea station",
    path: "https://your-tea-station.netlify.app/",
    text: "A simple tea site build using HTML/CSS only.",
    github: "https://github.com/chirag-08x/Tea-Station-Site",
    image: "./images/html-css-project-img/prjct-1.png",
  },
  {
    name: "backboards tours and travels",
    path: "https://backroad-travels.netlify.app/",
    text: "A simple tour and travels site built using HTML/CSS only.",
    github: "https://github.com/chirag-08x/BackBoards-Tour-Company",
    image: "./images/html-css-project-img/prjct-2.png",
  },
];

export default projects;
